# Generated by Django 3.1.6 on 2021-02-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='url',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
